import bitstring

MAX_WIDTH = 26

text_words = {
    "Attack " : 	"\xD6\x00",
    "Angel " : 	"\xD6\x01",
    "After " : 	"\xD6\x02",
    "Aura " : 	"\xD6\x03",
    "Ankor " : 	"\xD6\x04",
    "Black " : 	"\xD6\x05",
    "Bill: " : 	"\xD6\x06",
    "Crystal " : 	"\xD6\x07",
    "City " : 	"\xD6\x08",
    "Come " : 	"\xD6\x09",
    "Condor's " : 	"\xD6\x0A",
    "Change " : 	"\xD6\x0B",
    "Dark " : 	"\xD6\x0C",
    "Don't " : 	"\xD6\x0D",
    "Diamond " : 	"\xD6\x0E",
    "Drifting, " : 	"\xD6\x0F",
    "Eric: " : 	"\xD6\x10",
    "Edward " : 	"\xD6\x11",
    "Even " : 	"\xD6\x12",
    "Elder2f " : 	"\xD6\x13",
    "Earth " : 	"\xD6\x14",
    "Freedan's " : 	"\xD6\x15",
    "Great " : 	"\xD6\x16",
    "Grandma " : 	"\xD6\x17",
    "Good. " : 	"\xD6\x18",
    "Gold " : 	"\xD6\x19",
    "Grandpa " : 	"\xD6\x1A",
    "Hieroglyph " : 	"\xD6\x1B",
    "Hey, " : 	"\xD6\x1C",
    "It's " : 	"\xD6\x1D",
    "Inca " : 	"\xD6\x1E",
    "I'll " : 	"\xD6\x1F",
    "I've " : 	"\xD6\x20",
    "Itorie " : 	"\xD6\x21",
    "Jewels " : 	"\xD6\x22",
    "Jewels! " : 	"\xD6\x23",
    "Just " : 	"\xD6\x24",
    "Kara: " : 	"\xD6\x25",
    "Kara " : 	"\xD6\x26",
    "King " : 	"\xD6\x27",
    "Knight " : 	"\xD6\x28",
    "Karen's " : 	"\xD6\x29",
    "Lilly: " : 	"\xD6\x2A",
    "Let's " : 	"\xD6\x2B",
    "Lilly " : 	"\xD6\x2C",
    "Lola's " : 	"\xD6\x2D",
    "Lola: " : 	"\xD6\x2E",
    "Mystery " : 	"\xD6\x2F",
    "Maybe " : 	"\xD6\x30",
    "Moon " : 	"\xD6\x31",
    "Man: " : 	"\xD6\x32",
    "Morris's " : 	"\xD6\x33",
    "Melody " : 	"\xD6\x34",
    "Morris: " : 	"\xD6\x35",
    "Neil: " : 	"\xD6\x36",
    "Neil's " : 	"\xD6\x37",
    "Only " : 	"\xD6\x38",
    "Once " : 	"\xD6\x39",
    "Oink " : 	"\xD6\x3A",
    "Please " : 	"\xD6\x3B",
    "Psycho " : 	"\xD6\x3C",
    "People " : 	"\xD6\x3D",
    "Prayer " : 	"\xD6\x3E",
    "Pyramid " : 	"\xD6\x3F",
    "Purification " : 	"\xD6\x40",
    "Plate " : 	"\xD6\x41",
    "Quit " : 	"\xD6\x42",
    "Rob: " : 	"\xD6\x43",
    "Rolek " : 	"\xD6\x44",
    "Soldier: " : 	"\xD6\x45",
    "Strange " : 	"\xD6\x46",
    "South " : 	"\xD6\x47",
    "Statue " : 	"\xD6\x48",
    "Somehow " : 	"\xD6\x49",
    "Sometimes " : 	"\xD6\x4A",
    "Something " : 	"\xD6\x4B",
    "Shadow's " : 	"\xD6\x4C",
    "Someone " : 	"\xD6\x4D",
    "This " : 	"\xD6\x4E",
    "Will: " : 	"\xD6\x4F",
    "There's " : 	"\xD6\x50",
    "Will's " : 	"\xD6\x51",
    "There " : 	"\xD6\x52",
    "That's " : 	"\xD6\x53",
    "Tower " : 	"\xD6\x54",
    "They " : 	"\xD6\x55",
    "Then " : 	"\xD6\x56",
    "Trip " : 	"\xD6\x57",
    "Thank " : 	"\xD6\x58",
    "Take " : 	"\xD6\x59",
    "Will. " : 	"\xD6\x5A",
    "That " : 	"\xD6\x5B",
    "Will, " : 	"\xD6\x5C",
    "They're " : 	"\xD6\x5D",
    "These " : 	"\xD6\x5E",
    "Vampire " : 	"\xD6\x5F",
    "Village. " : 	"\xD6\x60",
    "When " : 	"\xD6\x61",
    "What " : 	"\xD6\x62",
    "Well, " : 	"\xD6\x63",
    "What's " : 	"\xD6\x64",
    "Where " : 	"\xD6\x65",
    "Woman: " : 	"\xD6\x66",
    "You've " : 	"\xD6\x67",
    "Your " : 	"\xD6\x68",
    "You're " : 	"\xD6\x69",
    "Yes, " : 	"\xD6\x6A",
    "about " : 	"\xD6\x6B",
    "anything " : 	"\xD6\x6C",
    "around " : 	"\xD6\x6D",
    "another " : 	"\xD6\x6E",
    "ancient " : 	"\xD6\x6F",
    "been " : 	"\xD6\x70",
    "become " : 	"\xD6\x71",
    "body " : 	"\xD6\x72",
    "back " : 	"\xD6\x73",
    "before " : 	"\xD6\x74",
    "brought " : 	"\xD6\x75",
    "beautiful " : 	"\xD6\x76",
    "being " : 	"\xD6\x77",
    "can't " : 	"\xD6\x78",
    "come " : 	"\xD6\x79",
    "could " : 	"\xD6\x7A",
    "comet " : 	"\xD6\x7B",
    "company " : 	"\xD6\x7C",
    "children " : 	"\xD6\x7D",
    "constellation " : 	"\xD6\x7E",
    "changed " : 	"\xD6\x7F",
    "came " : 	"\xD6\x80",
    "coming " : 	"\xD6\x81",
    "don't " : 	"\xD6\x82",
    "didn't " : 	"\xD6\x83",
    "doesn't " : 	"\xD6\x84",
    "distant " : 	"\xD6\x85",
    "different " : 	"\xD6\x86",
    "demons " : 	"\xD6\x87",
    "destroy " : 	"\xD6\x88",
    "everyone " : 	"\xD6\x89",
    "explorer " : 	"\xD6\x8A",
    "everyone's " : 	"\xD6\x8B",
    "enemies " : 	"\xD6\x8C",
    "exposed " : 	"\xD6\x8D",
    "from " : 	"\xD6\x8E",
    "found " : 	"\xD6\x8F",
    "find " : 	"\xD6\x90",
    "feel " : 	"\xD6\x91",
    "father's " : 	"\xD6\x92",
    "going " : 	"\xD6\x93",
    "good " : 	"\xD6\x94",
    "great " : 	"\xD6\x95",
    "ground " : 	"\xD6\x96",
    "give " : 	"\xD6\x97",
    "have " : 	"\xD6\x98",
    "heard " : 	"\xD6\x99",
    "human " : 	"\xD6\x9A",
    "hear " : 	"\xD6\x9B",
    "huge " : 	"\xD6\x9C",
    "happened " : 	"\xD6\x9D",
    "hieroglyph " : 	"\xD6\x9E",
    "it's " : 	"\xD6\x9F",
    "inventory " : 	"\xD6\xA0",
    "into " : 	"\xD6\xA1",
    "inside " : 	"\xD6\xA2",
    "just " : 	"\xD6\xA3",
    "know " : 	"\xD6\xA4",
    "like " : 	"\xD6\xA5",
    "long " : 	"\xD6\xA6",
    "little " : 	"\xD6\xA7",
    "light " : 	"\xD6\xA8",
    "look " : 	"\xD6\xA9",
    "looks " : 	"\xD6\xAA",
    "looking " : 	"\xD6\xAB",
    "leave " : 	"\xD6\xAC",
    "labor " : 	"\xD6\xAD",
    "left " : 	"\xD6\xAE",
    "live " : 	"\xD6\xAF",
    "life " : 	"\xD6\xB0",
    "living " : 	"\xD6\xB1",
    "must " : 	"\xD6\xB2",
    "made " : 	"\xD6\xB3",
    "melody " : 	"\xD6\xB4",
    "move " : 	"\xD6\xB5",
    "many " : 	"\xD6\xB6",
    "more " : 	"\xD6\xB7",
    "matter " : 	"\xD6\xB8",
    "nothing " : 	"\xD6\xB9",
    "need " : 	"\xD6\xBA",
    "never " : 	"\xD6\xBB",
    "next " : 	"\xD6\xBC",
    "other " : 	"\xD6\xBD",
    "over " : 	"\xD6\xBE",
    "outside " : 	"\xD6\xBF",
    "original " : 	"\xD6\xC0",
    "people " : 	"\xD6\xC1",
    "power " : 	"\xD6\xC2",
    "present. " : 	"\xD6\xC3",
    "playing " : 	"\xD6\xC4",
    "raised " : 	"\xD6\xC5",
    "right-hand " : 	"\xD6\xC6",
    "strange " : 	"\xD6\xC7",
    "something " : 	"\xD6\xC8",
    "statue " : 	"\xD6\xC9",
    "should " : 	"\xD6\xCA",
    "started " : 	"\xD6\xCB",
    "seems " : 	"\xD6\xCC",
    "same " : 	"\xD6\xCD",
    "such " : 	"\xD6\xCE",
    "someone " : 	"\xD6\xCF",
    "some " : 	"\xD6\xD0",
    "save " : 	"\xD6\xD1",
    "statues " : 	"\xD6\xD2",
    "still " : 	"\xD6\xD3",
    "said " : 	"\xD6\xD4",
    "stands " : 	"\xD6\xD5",
    "this " : 	"\xD6\xD6",
    "that " : 	"\xD6\xD7",
    "thought " : 	"\xD6\xD8",
    "there " : 	"\xD6\xD9",
    "think " : 	"\xD6\xDA",
    "there's " : 	"\xD6\xDB",
    "through " : 	"\xD6\xDC",
    "tried " : 	"\xD6\xDD",
    "terrible " : 	"\xD6\xDE",
    "time " : 	"\xD6\xDF",
    "things " : 	"\xD6\xE0",
    "their " : 	"\xD6\xE1",
    "town " : 	"\xD6\xE2",
    "thing " : 	"\xD6\xE3",
    "these " : 	"\xD6\xE4",
    "temple " : 	"\xD6\xE5",
    "them " : 	"\xD6\xE6",
    "take " : 	"\xD6\xE7",
    "turned, " : 	"\xD6\xE8",
    "understand " : 	"\xD6\xE9",
    "under " : 	"\xD6\xEA",
    "underwater " : 	"\xD6\xEB",
    "village " : 	"\xD6\xEC",
    "very " : 	"\xD6\xED",
    "voice " : 	"\xD6\xEE",
    "will " : 	"\xD6\xEF",
    "with " : 	"\xD6\xF0",
    "want " : 	"\xD6\xF1",
    "were " : 	"\xD6\xF2",
    "would " : 	"\xD6\xF3",
    "where " : 	"\xD6\xF4",
    "world " : 	"\xD6\xF5",
    "when " : 	"\xD6\xF6",
    "what " : 	"\xD6\xF7",
    "without " : 	"\xD6\xF8",
    "wonder " : 	"\xD6\xF9",
    "won't " : 	"\xD6\xFA",
    "wouldn't " : 	"\xD6\xFB",
    "wanted " : 	"\xD6\xFC",
    "waiting " : 	"\xD6\xFD",
    "your " : 	"\xD6\xFE",
    "you're " : 	"\xD6\xFF",
    "1994 " : 	"\xD7\x00",
    "Actually, " : 	"\xD7\x01",
    "Button " : 	"\xD7\x02",
    "Buttons " : 	"\xD7\x03",
    "Back " : 	"\xD7\x04",
    "Child: " : 	"\xD7\x05",
    "Defeating " : 	"\xD7\x06",
    "Didn't " : 	"\xD7\x07",
    "Desert " : 	"\xD7\x08",
    "Erasquez: " : 	"\xD7\x09",
    "Elder " : 	"\xD7\x0A",
    "Earth's " : 	"\xD7\x0B",
    "Eric's " : 	"\xD7\x0C",
    "Everybody " : 	"\xD7\x0D",
    "Flute: " : 	"\xD7\x0E",
    "First " : 	"\xD7\x0F",
    "Firebird, " : 	"\xD7\x10",
    "From " : 	"\xD7\x11",
    "Gaia, " : 	"\xD7\x12",
    "Gorgon " : 	"\xD7\x13",
    "Have " : 	"\xD7\x14",
    "Hey! " : 	"\xD7\x15",
    "Istar's " : 	"\xD7\x16",
    "Ishtar's " : 	"\xD7\x17",
    "Lilly's " : 	"\xD7\x18",
    "Larai " : 	"\xD7\x19",
    "Looking " : 	"\xD7\x1A",
    "Main " : 	"\xD7\x1B",
    "Man's " : 	"\xD7\x1C",
    "Memory " : 	"\xD7\x1D",
    "Mountain " : 	"\xD7\x1E",
    "Morris " : 	"\xD7\x1F",
    "Many " : 	"\xD7\x20",
    "Native " : 	"\xD7\x21",
    "Native's " : 	"\xD7\x22",
    "Neil " : 	"\xD7\x23",
    "Naska " : 	"\xD7\x24",
    "Power " : 	"\xD7\x25",
    "Prison " : 	"\xD7\x26",
    "Play " : 	"\xD7\x27",
    "Panther's " : 	"\xD7\x28",
    "Rob's " : 	"\xD7\x29",
    "Recently " : 	"\xD7\x2A",
    "Restores " : 	"\xD7\x2B",
    "Right " : 	"\xD7\x2C",
    "Russian " : 	"\xD7\x2D",
    "Rofsky " : 	"\xD7\x2E",
    "Rearrange " : 	"\xD7\x2F",
    "Special " : 	"\xD7\x30",
    "Spin " : 	"\xD7\x31",
    "Seaside " : 	"\xD7\x32",
    "She's " : 	"\xD7\x33",
    "Shall " : 	"\xD7\x34",
    "Sorry " : 	"\xD7\x35",
    "Select " : 	"\xD7\x36",
    "Show " : 	"\xD7\x37",
    "Soon " : 	"\xD7\x38",
    "Will! " : 	"\xD7\x39",
    "Will... " : 	"\xD7\x3A",
    "Tell " : 	"\xD7\x3B",
    "Uses " : 	"\xD7\x3C",
    "Wind " : 	"\xD7\x3D",
    "We'll " : 	"\xD7\x3E",
    "We're " : 	"\xD7\x3F",
    "With " : 	"\xD7\x40",
    "We've " : 	"\xD7\x41",
    "Wait " : 	"\xD7\x42",
    "Watermia. " : 	"\xD7\x43",
    "always " : 	"\xD7\x44",
    "approaching " : 	"\xD7\x45",
    "animals " : 	"\xD7\x46",
    "almost " : 	"\xD7\x47",
    "also " : 	"\xD7\x48",
    "anything. " : 	"\xD7\x49",
    "abolition " : 	"\xD7\x4A",
    "breath " : 	"\xD7\x4B",
    "birthday " : 	"\xD7\x4C",
    "best " : 	"\xD7\x4D",
    "bring " : 	"\xD7\x4E",
    "bouquet " : 	"\xD7\x4F",
    "better " : 	"\xD7\x50",
    "behind " : 	"\xD7\x51",
    "change " : 	"\xD7\x52",
    "castle " : 	"\xD7\x53",
    "called " : 	"\xD7\x54",
    "comet's " : 	"\xD7\x55",
    "condition. " : 	"\xD7\x56",
    "care " : 	"\xD7\x57",
    "door " : 	"\xD7\x58",
    "destroyed " : 	"\xD7\x59",
    "disappeared " : 	"\xD7\x5A",
    "discovered " : 	"\xD7\x5B",
    "dark " : 	"\xD7\x5C",
    "ever " : 	"\xD7\x5D",
    "elevator " : 	"\xD7\x5E",
    "explorer. " : 	"\xD7\x5F",
    "eyes " : 	"\xD7\x60",
    "first " : 	"\xD7\x61",
    "fish " : 	"\xD7\x62",
    "followed " : 	"\xD7\x63",
    "fountain " : 	"\xD7\x64",
    "floor " : 	"\xD7\x65",
    "finally " : 	"\xD7\x66",
    "father " : 	"\xD7\x67",
    "flower " : 	"\xD7\x68",
    "forced " : 	"\xD7\x69",
    "forget " : 	"\xD7\x6A",
    "fate " : 	"\xD7\x6B",
    "girl " : 	"\xD7\x6C",
    "gets " : 	"\xD7\x6D",
    "guess " : 	"\xD7\x6E",
    "girl's " : 	"\xD7\x6F",
    "house " : 	"\xD7\x70",
    "hope " : 	"\xD7\x71",
    "home " : 	"\xD7\x72",
    "here " : 	"\xD7\x73",
    "here. " : 	"\xD7\x74",
    "home! " : 	"\xD7\x75",
    "happen.... " : 	"\xD7\x76",
    "houses " : 	"\xD7\x77",
    "inventing " : 	"\xD7\x78",
    "last " : 	"\xD7\x79",
    "lost " : 	"\xD7\x7A",
    "language. " : 	"\xD7\x7B",
    "list " : 	"\xD7\x7C",
    "life. " : 	"\xD7\x7D",
    "laborer " : 	"\xD7\x7E",
    "letter " : 	"\xD7\x7F",
    "looked " : 	"\xD7\x80",
    "lose " : 	"\xD7\x81",
    "left-hand " : 	"\xD7\x82",
    "mushrooms " : 	"\xD7\x83",
    "make " : 	"\xD7\x84",
    "mother " : 	"\xD7\x85",
    "merchants " : 	"\xD7\x86",
    "meet " : 	"\xD7\x87",
    "most " : 	"\xD7\x88",
    "only " : 	"\xD7\x89",
    "ocean " : 	"\xD7\x8A",
    "opened " : 	"\xD7\x8B",
    "outskirts " : 	"\xD7\x8C",
    "president " : 	"\xD7\x8D",
    "please " : 	"\xD7\x8E",
    "probably " : 	"\xD7\x8F",
    "place " : 	"\xD7\x90",
    "prison " : 	"\xD7\x91",
    "pretty " : 	"\xD7\x92",
    "palace " : 	"\xD7\x93",
    "right " : 	"\xD7\x94",
    "really " : 	"\xD7\x95",
    "returned " : 	"\xD7\x96",
    "running " : 	"\xD7\x97",
    "ruins " : 	"\xD7\x98",
    "right. " : 	"\xD7\x99",
    "ruins, " : 	"\xD7\x9A",
    "road " : 	"\xD7\x9B",
    "rest " : 	"\xD7\x9C",
    "stone " : 	"\xD7\x9D",
    "seem " : 	"\xD7\x9E",
    "scattered " : 	"\xD7\x9F",
    "seemed " : 	"\xD7\xA0",
    "softly " : 	"\xD7\xA1",
    "soldiers " : 	"\xD7\xA2",
    "shape " : 	"\xD7\xA3",
    "since " : 	"\xD7\xA4",
    "surprised " : 	"\xD7\xA5",
    "sure " : 	"\xD7\xA6",
    "seen " : 	"\xD7\xA7",
    "shouldn't " : 	"\xD7\xA8",
    "somewhere " : 	"\xD7\xA9",
    "times " : 	"\xD7\xAA",
    "they " : 	"\xD7\xAB",
    "talk " : 	"\xD7\xAC",
    "tell " : 	"\xD7\xAD",
    "townspeople " : 	"\xD7\xAE",
    "taken " : 	"\xD7\xAF",
    "they're " : 	"\xD7\xB0",
    "travelling " : 	"\xD7\xB1",
    "trying " : 	"\xD7\xB2",
    "turned " : 	"\xD7\xB3",
    "temporary " : 	"\xD7\xB4",
    "than " : 	"\xD7\xB5",
    "then " : 	"\xD7\xB6",
    "too, " : 	"\xD7\xB7",
    "thousands " : 	"\xD7\xB8",
    "turn " : 	"\xD7\xB9",
    "treasure, " : 	"\xD7\xBA",
    "used " : 	"\xD7\xBB",
    "until " : 	"\xD7\xBC",
    "village. " : 	"\xD7\xBD",
    "vampire " : 	"\xD7\xBE",
    "while " : 	"\xD7\xBF",
    "water " : 	"\xD7\xC0",
    "went " : 	"\xD7\xC1",
    "wondered " : 	"\xD7\xC2",
    "written " : 	"\xD7\xC3",
    "woman " : 	"\xD7\xC4",
    "wind " : 	"\xD7\xC5",
    "years " : 	"\xD7\xC6",
    "you. " : 	"\xD7\xC7"
}

text_letters = {
    "?" : 	"\x0D",
    "'" : 	"\x0E",
    "0" : 	"\x20",
    "1" : 	"\x21",
    "2" : 	"\x22",
    "3" : 	"\x23",
    "4" : 	"\x24",
    "5" : 	"\x25",
    "6" : 	"\x26",
    "7" : 	"\x27",
    "8" : 	"\x28",
    "9" : 	"\x29",
    "." : 	"\x2A",
    "," : 	"\x2B",
    ">" : 	"\x2C",
#    '"' : 	"\x2D",
#    '"' : 	"\x2E",
    ":" : 	"\x2F",
    "A" : 	"\x40",
    "B" : 	"\x41",
    "C" : 	"\x42",
    "D" : 	"\x43",
    "E" : 	"\x44",
    "F" : 	"\x45",
    "G" : 	"\x46",
    "H" : 	"\x47",
    "I" : 	"\x48",
    "J" : 	"\x49",
    "K" : 	"\x4A",
    "L" : 	"\x4B",
    "M" : 	"\x4C",
    "N" : 	"\x4D",
    "O" : 	"\x4E",
    "!" : 	"\x4F",
    "P" : 	"\x60",
    "Q" : 	"\x61",
    "R" : 	"\x62",
    "S" : 	"\x63",
    "T" : 	"\x64",
    "U" : 	"\x65",
    "V" : 	"\x66",
    "W" : 	"\x67",
    "X" : 	"\x68",
    "Y" : 	"\x69",
    "Z" : 	"\x6A",
    "/" : 	"\x6B",
    "*" : 	"\x6C",
    "-" : 	"\x6D",
    "(" : 	"\x6E",
    ")" : 	"\x6F",
    "a" : 	"\x80",
    "b" : 	"\x81",
    "c" : 	"\x82",
    "d" : 	"\x83",
    "e" : 	"\x84",
    "f" : 	"\x85",
    "g" : 	"\x86",
    "h" : 	"\x87",
    "i" : 	"\x88",
    "j" : 	"\x89",
    "k" : 	"\x8A",
    "l" : 	"\x8B",
    "m" : 	"\x8C",
    "n" : 	"\x8D",
    "o" : 	"\x8E",
    "p" : 	"\xA0",
    "q" : 	"\xA1",
    "r" : 	"\xA2",
    "s" : 	"\xA3",
    "t" : 	"\xA4",
    "u" : 	"\xA5",
    "v" : 	"\xA6",
    "w" : 	"\xA7",
    "x" : 	"\xA8",
    "y" : 	"\xA9",
    "z" : 	"\xAA",
    "," : 	"\xAB",
    " " : 	"\xAC",
    "|" : 	"\xCF"    # Prompts for advance
}

text_words_inv = {v: k for k, v in text_words.items()}
text_letters_inv = {v: k for k, v in text_letters.items()}

def get_text(addr,f,rom_offset=0):
    str_encoded = ""
    f.seek(addr+rom_offset)
    char = ""
    bytes = 0
    while char != "\xC0" and char != "\xCA":
        char = f.read(1)
        str_encoded += char
        bytes += 1

    str_decoded = ""
    i = 0
    while i < len(str_encoded):
        byte = str_encoded[i]
        i += 1
        if byte not in ["\xD3","\xC0","\xCA"]:
            if byte in ["\xD6","\xD7"]:
                word = byte + str_encoded[i]
                i += 1
                if word in text_words_inv:
                    str_decoded += text_words_inv[word]
                #else:
                    #print "WARNING: Word not recognized >>", word
            elif byte in text_letters_inv:
                str_decoded += text_letters_inv[byte]
            elif byte not in ["\xcb"]:
                str_decoded += "?"
                #print "WARNING: Letter not recognized >>", byte

    #print str_decoded
    return [str_decoded, bytes]

def encode(str,full_box=False):
    words = []
    word = ""
    i = 0
    while i < len(str):
        char = str[i]
        word += char
        if char == " " or i == len(str)-1:
            words.append(word)
            word = ""
        i += 1

    #print words
    if full_box:
        str_encoded = "\xd3"
    else:
        str_encoded = ""
    text_width = 0

    for word in words:
        if len(word) > MAX_WIDTH:
            print "ERROR: Word too long >>", word
            return ""
        text_width += len(word)
        if text_width > MAX_WIDTH:
            str_encoded += "\xCB"
            text_width = len(word)
        if word in text_words:
            str_encoded += text_words[word]
        else:
            i = 0
            while i < len(word):
                char = word[i]
                if char in text_letters:
                    str_encoded += text_letters[char]
                else:
                    str_encoded += "\x0D"
                    print "WARNING: Character not recognized >>", char
                i += 1

    if full_box:
        str_encoded += "\xc0"

    #print str_encoded, len(str_encoded)
    return str_encoded
