name: Bug report
description: |
  Found a bug, an issue, something completely broken ?
  Don't worry, tell us and we will look at it.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # IoGR Bug Report
        
        Thank you for reaching out to us about a bug on the randomizer, please take a few moment to give us as many information as you can.
        
        ## Important
        
        Before anything if what your describe ends up being a vanilla game bug, we will just close the issue. We only tackle randomizer based bugs.
        
        ## Contact
        
        Most of the team work through discord join us there so that we may help you and more ! 
        [![Discord](https://img.shields.io/discord/558423526772834329?style=for-the-badge&logo=discord&logoColor=white&label=Illusion%20of%20Gaia%20Randomizer&labelColor=%235865F2)](https://discord.gg/TQEyBvu)

  - type: input
    id: discord-id
    attributes:
      label: Please put your discord username here so that we can contact you.
  - type: markdown
    attributes:
      value: |
        ## Randomizer information
        We will now begin with some information on which version of the game you played
  - type: dropdown
    id: source
    attributes:
      label: Which version of the randomizer did you use ?
      options:
        - From the main site iogr.app
        - From the dev site dev.iogr.app
        - Directly from sources
        - I don't know
      default: 0
    validations:
      required: true
  - type: input
    id: source-version
    attributes:
      label: Which numeral version of the randomizer did you use ? (Client version on the website, tag / commit from source)
      placeholder: v4.3.0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks, now lets walk through your issue.
        ## Settings
  - type: input
    id: seed-permalink
    attributes:
      label: If you have a permalink to a seed please add it here
      placeholder: https://iogr.app/permalink/xxxxxxxxx
  - type: textarea
    id: settings-description
    attributes:
      label: Could you give us a list of settings you used ?
      placeholder: |
        I played X statues game choice, with Open world and some enemizer, ...
  - type: markdown
    attributes:
      value: |
        Thanks, now lets walk through your issue.
        ## Issue description
  - type: dropdown
    id: issue-type
    attributes:
      label: Which type of issue did you encounter ?
      options:
        - General gameplay softlock / I can't finish my seed
        - Game state corruption / Something broke in the game and I can't play
        - Seed generation failure / I can't get the settings I chose to work together
        - Glitched graphics / Something wrong appear on my screen
        - Sound issues / Some sounds should or should not play
        - QoL not working / Things does not work as intended
        - Website does not work
        - Other
      default: 6
  - type: textarea
    id: issue-description
    attributes:
      label: Now please describe your issue
      placeholder: When I was doing ....
    validations:
      required: true
  - type: textarea
    id: issue-reproduction
    attributes:
      label: How can we reproduce the issue ?
      placeholder: |
        Please describe the list of action that reproduce your issue if you can.
        You can add a link to a video recording of the issue for use to get a better idea of what happened
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this issue, we will look at it and get back to you.
        Have a nice day.